### ISSUE TITLE
Fix progress bar (and other styling)

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_nodejs_app#10]
Fix styling issues:

* [x] Busy indicator appears at bottom of page, doesn't animate and doesn't disappear.
* [x] Font sizes are different than dashboard in Notebook.
* [x] Stream message outputs get appended as new elements in output area
    * When `phosphor-widget` is updated to `1.0.0-rc1` or later, re-commit 94d734dc37f706fd9832eb59e7ed2654bdab3608.
* [x] Output area overlaps widget area, but only when running from Docker container (not from `localhost`).

**Comment by dalogsdon** [comment]
All obvious styling differences seen with the simple dashboard have been fixed. As we add more widget support we will continue to fix styling discrepancies.

**Comment by jhpedemonte** [comment]
Our fix for the output area didn't work correctly because of an issue in the `phosphor-widget` dependency. Need to wait for its latest code to be tagged. For now, we've backed out that fix (94d734dc37f706fd9832eb59e7ed2654bdab3608).

**Comment by parente** [comment]
@sccolbert @blink1073 Any idea when you might cut RC1 of phosphor-widget?

**Comment by sccolbert** [comment]
@parente I can cut an `rc.1` at any time, but there have been no functional changes since `rc.0`. Are you needing something specific?

**Comment by dalogsdon** [comment]
@sccolbert We are needing https://github.com/phosphorjs/phosphor-widget/commit/28ee2e76a163b568574f7fc2a743ef257448132a

**Comment by blink1073** [comment]
That config does not affect Webpack.

**Comment by sccolbert** [comment]
@dalogsdon As Steve said, that package setting only affects the browserify CSS transform. It has no bearing on webpack. Are you seeing something which doesn't work with the `rc.0`?

**Comment by blink1073** [comment]
Ah, you're using Browserify, I was confused by the Webpack file.

**Comment by blink1073** [comment]
They're using a separate transform step in gulp, looks like the browserify config interferes with it.

**Comment by sccolbert** [comment]
Ah. Yet another reason to not use browserify :)

**Comment by sccolbert** [comment]
The `rc.1` is now published.

**Comment by dalogsdon** [comment]
@blink1073 We are using both browserify and webpack at the moment, and yes it was interfering and causing an error which I don't have handy at the moment. 

@sccolbert Thanks for the `rc.1`, we'll give it another go now.

**Comment by jhpedemonte** [comment]
Overlap in dashboard seems to be related to `lodash` version, somehow! No overlap with v3.5.0, but yes with v4.1.0.

**Comment by parente** [comment]
Fixed by latest PR.
