### ISSUE TITLE
Allow dashboard server to send auth headers to kernel gateway

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#20]
1. ~~tmpnb might be configured to require an auth token to request a KG server~~
2. KG server might be configured to require an auth token to request a kernel

Assume both of these keys can be set once at server start time via nconf, and just pass them along where appropriate. The keys should NOT be exposed to the frontend client.

* [x] Pass auth token to kernel gateway
* ~~Pass auth token to tmpnb~~
* [x] Tests?

**Comment by parente** [comment]
Let's just worry about KG token to start. tmpnb is going to be harder work with than expected because of the route to instance mapping needed in #11. We can open another item later to address tmpnb.

**Comment by jhpedemonte** [comment]
In that case, ready for review. @dalogsdon, can you take a look?

**Comment by parente** [comment]
Fixed by PR #26
