### ISSUE TITLE
Dashboard backend can proxy to KGs that don't run at root of domain

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#21]
Kernel gateway supports a base_url parameter that allows it to run under non-root paths. This is necessary when it's deployed using something like tmpnb which runs multiple instances of the KG.

Make sure the dashboard server can:

* [x] Proxy to a single kernel gateway that is running under a custom base_url
* ~~[ ] Respects the URL returned by tmpnb's /api/spawn (see #11)~~

**Comment by dalogsdon** [comment]
For part 1, I presume we add the option to set a KG_BASE_URL env var when running `make run-kernel-gateway` and then use that base url in the KERNEL_GATEWAY_URL? Is the kernel gateway URL then of the form `KG_IP/KG_BASE_URL`? For example, `/api/kernels` becomes `/base_url/api/kernels`?

**Comment by parente** [comment]
In KG and notebook, the base_url should be of the form `/foo/bar'. That said, @jtyberg made KG more robust in handling cases like `foo/bar` and `/foo/bar/' by normalizing them to the preferred `/foo/bar` form. Node app should do the same.

**Comment by parente** [comment]
Ignore the tmpnb part for now.

**Comment by parente** [comment]
Fixed by PR #30
