### ISSUE TITLE
Get a simple declarative widgets demo working

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#23]
Try to get declarative widgets working on top of the bleeding edge ipywidgets we're using here already.

/cc @lbustelo

**Comment by lbustelo** [comment]
Take a look at https://github.com/jupyter-incubator/declarativewidgets/pull/157
There were many changes to get things to function.

**Comment by parente** [comment]
I think the point of this exercise is to get things working in a PR here with whatever shims it takes, and then figure out what issues/PRs to open against widgets in terms of API that has to be exposed so that the shims can eventually go away.

Example: The dashboard frontend code needs to create and own the jupyter-js-services kernel client to send kernel requests to the backend. Decl widgets probably needs a way for the app to (optionally) pass that ref through on decl widget init (dependency inject) and only create things itself if one is not provided (if ever).

What else needs to be done in declarative widgets master assuming all the ipywidgets, jupyter-js-widgets, phosphor-widgets, etc. stuff settles down and becomes easily installable later?

**Comment by parente** [comment]
Basic demos are working (and then some). We'll get to deploying decl widget notebooks later.
