### ISSUE TITLE
NodeJS app should send kernel shutdown when client websocket disconnects

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#25]
Most likely fix, call the jupyter-js-services shutdown method for the disconnecting websocket instance here: https://github.com/jupyter-incubator/dashboards_nodejs_app/blob/5ace686d7efd80eb1f70f3f8fc658c5a72504bf8/routes/api.js#L154 and in other errors cases too.

**Comment by jtyberg** [comment]
I could be mistaken, but jupyter-js-services is a frontend lib?  We don't have a handle to the kernel object on the backend.  

If a user closes the browser window/tab, the backend proxy gets an on close event about a minute later.  

We could associate the kernel/session ID with each client on the backend, and once the client connection closes, we could tell the kernel_gateway to kill the kernel/session by this ID.  We're looking into what information gets passed to the proxy on close event to see if we can even identify the client that's being disconnected.

**Comment by parente** [comment]
Yes. You're right. The jupyter-js-services is not on the backend. In some earlier rendition, we talked about having it there too, but the backend wound up being just a proxy.

@jhpedemonte mentioned the `x-jupyter-session-id` header as the way to link client to connection.

**Comment by jhpedemonte** [comment]
> jupyter-js-services is a frontend lib?

It's agnostic -- it can also be used on backend.
