### ISSUE TITLE
Option to support https

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#3]
Allow specification of the key and cert via nconf supported parameters.

**Comment by poplav** [comment]
Pull Request #14 should resolve this issue.

**Comment by jhpedemonte** [comment]
Merged @poplav's PR. One addition that would be nice: when loading HTTP, I get an error. Would be better to just redirect to HTTPS.

**Comment by parente** [comment]
Redirect +1.

**Comment by poplav** [comment]
@jhpedemonte , #16 creates an http server along with the https server.  When a request goes to the http server the url location is set to point to the https server.

**Comment by parente** [comment]
Rebased this AM. Decided in a chat that, for now, the Docker internal ports must match the Docker external ports to let the redirect only require two env vars instead of three (with the third being the external redirect port if we allowed arbitrary Docker mappings.) We can revisit more config later.

**Comment by parente** [comment]
Merged in PR #16.
