### ISSUE TITLE
Do something less yucky at /

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#32]
Right now, it's a vanilla page with text that says "List of notebooks". 

* [x] Pretty it up to have the banner like the dashboard pages have when auth is enabled. 
* [x] Show a bootstrap styled list of dashboard links
* [x] If there's a dashboard notebook called index.ipynb, redirect immediately to that instead of showing the list?

**Comment by poplav** [comment]
PR #35 should resolve this issue.
