### ISSUE TITLE
Error handling seems off

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_nodejs_app#37]
I'm now seeing a lot of these types of error in the server console:

```
STACK: Error: Not Found
    at /home/node/app/app.js:105:15
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/node/app/node_modules/express/lib/router/index.js:312:13)
    at /home/node/app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:330:12)
    at next (/home/node/app/node_modules/express/lib/router/index.js:271:10)
    at /home/node/app/node_modules/express/lib/router/index.js:618:15
    at next (/home/node/app/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/home/node/app/node_modules/express/lib/router/index.js:176:3)
    at router (/home/node/app/node_modules/express/lib/router/index.js:46:12)
GET /components/index.js.map 404 2.301 ms - 878
```

They don't really say much about what's going on. It just seems to be a generic error handler.  @dalogsdon, I think we need to revisit how these error handlers are setup in the express app.

**Comment by parente** [comment]
It looks like they're firing when the the browser tries to load the JS map files for the compressed JS. If that's so, then agreed, there's something funky with the error logging config.

**Comment by jtyberg** [comment]
I think we're seeing all the extra stack traces because the 404 handler is passing onto the next handler, which is doing the extra logging.  The 404 handler should probably just return the 404 back to the client.

https://github.com/jupyter-incubator/dashboards_nodejs_app/blob/master/app.js#L108

**Comment by poplav** [comment]
I opened #54 which passes a more detailed error message to that next handler on a 404.  The next handler will print the error message and print the stack trace if it is not a 404 error.  We have other error handling mechanisms that wouldn't go through here in index.js and api.js.

**Comment by jtyberg** [comment]
Do we need a more detailed message for 404?  It can't be found, OK, send it back. Request handled.  Don't pass it to the other handler.

**Comment by dalogsdon** [comment]
@jhpedemonte, @poplav and I had a brief offline discussion and decided it makes sense to only show stack trace for 500-level errors.

**Comment by parente** [comment]
+1 for traces on 500 only. Not sure if that also handles @jtyberg's 404 "just pass to next" concern.

**Comment by jtyberg** [comment]
Typical express route handling: if request is handled, be done with it. Don't pass it to the next handler, but we're passing it to the next handler.

**Comment by dalogsdon** [comment]
fyi, the original code (with the `next()` call) was generated by the [express generator](http://expressjs.com/en/starter/generator.html):

```javascript
// catch 404 and forward to error handler
app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
});
```

so it is the recommended pattern. I think the main concern here if removing the `next()` call is duplication of the rendering function:

```javascript
res.render('error', {
    ...options...
});
```

**Comment by parente** [comment]
Completed by #61
