### ISSUE TITLE
Option to support shared login

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#4]
Support optional username and password configuration options via any nconf allowed method on server startup. If one is required, make sure the other is specified as well. If both are set, check whether or not all HTTP requests have a valid session cookie. If the user has authed (i.e., session cook is present and valid), service the HTTP request. If the user has not authed (i.e., the cookie does not exist, is expired, is invalid), show a basic login page prompting the user for the configured username and password. On successful login, set a temporary (1 day?) session cookie.

Use of client-side session cookies is fine here. (I think they're the express default still.)

**Comment by parente** [comment]
@poplav has a branch that probably needs rebase after we merged master last Friday. Needs UI work to get the form prettied up.

**Comment by parente** [comment]
Also, verify that the middleware protects the /api/* routes (which are node-http-proxy based).

**Comment by parente** [comment]
Decided to go with boostrap for styling. Also looked into making sure that auth applies to all routes.

**Comment by poplav** [comment]
PR #29 should resolve the issue.

**Comment by parente** [comment]
@poplav I merged #29 but it would be good if you could fix one more styling nit: Align the logout text at its vertical middle with the title text.

![screen shot 2016-01-27 at 4 43 28 pm](https://cloud.githubusercontent.com/assets/153745/12629301/44f4ce9a-c515-11e5-901c-b8f4f402ba53.png)

**Comment by poplav** [comment]
@parente #34 Should fix the styling.  A screenshot is included in the PR.

**Comment by parente** [comment]
Fixed in #34. Thanks for merging @jhpedemonte

**Comment by parente** [comment]
Both @jhpedemonte and I forgot to test the no credentials case. If I do `make run` without any username or password, then the gray bar with sign in still apears. If I click sign in, I get a 500 error because auth endpoints are not enabled.

The fix: don't show the banner part of the template at all if auth is not enabled.
