### ISSUE TITLE
Separate programmatic API from UI endpoint

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#48]
* [x] `POST /notebooks` -> move to `POST /api/notebooks` and keep as the programmatic way to add a new notebook
* [x] `GET /` -> redirect and/or render `/dashboards/index.ipynb` if it exists or `/dashboards` if not. 
* [x] `GET /dashboards` -> UI list of all dashboards
* [x] `GET /dashboards/:name` -> notebook rendered as a dashboard

**Comment by parente** [comment]
Doh, right, can't use `/api` which is preserved for the proxying. Whoever gets this can figure out that part.

**Comment by dalogsdon** [comment]
I want to avoid attempting to elegantly overlay the 2 APIs, so I am going with @jhpedemonte's solution of `/api-2/notebooks` unless someone has a better name.

**Comment by jtyberg** [comment]
I would much prefer `/_api/notebooks`, as it implies some form of privacy.  I've seen it done before too, if that counts for anything.

**Comment by dalogsdon** [comment]
Sure, its better than having a number in there.

**Comment by parente** [comment]
_
