### ISSUE TITLE
Hide stderr / exception tracebacks in dashboard view

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#49]
Port of the styling added to `jupyter-incubator/dashboards` and `jupyter-incubator/dashboards_bundlers` recently.

**Comment by parente** [comment]
Nope. Not styling. Need to redirect certain types of output destined for jupyter-js-output-area.

**Comment by jhpedemonte** [comment]
In `/public/js/dashboard.js`, there's a `_consumeMessage` function which handles incoming messages and sends them to the OutputArea. One of the message types is `error`. Is that what you're looking for?

**Comment by dalogsdon** [comment]
The output area does not add many descriptive attributes, so it may need to be handled before hitting the output area consume function mentions above.
