### ISSUE TITLE
Cells overlapping again

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#57]
No console errors. Looks like something else broke gridstack. Confirmed that lodash is pinned. Even tried setting it to 3.10.1 exactly.

![screen shot 2016-02-04 at 10 24 28 am](https://cloud.githubusercontent.com/assets/153745/12819556/8933ff12-cb29-11e5-8cd2-4da3d90e2258.png)

**Comment by parente** [comment]
Fun fact: only broken with `make clean dev-install dev`. Works fine when starting with `make run` with a touch of bower.json to ensure the Docker build re-runs the bower command.

**Comment by jtyberg** [comment]
I wonder if `make dev-install` needs to add `npm run build`, which does the `gulp build` tasks like copying the web components into the appropriate directory, etc.

**Comment by parente** [comment]
Doh! Silly me assumed `make clean` was handling all the cleanup. Now that I look at the Makefile, that's a nope.  Will try, fix clean, and add the build step if that's the problem.

**Comment by jtyberg** [comment]
I added `npm run build` to the `make dev-install` target (for other reasons), and it's working fine for me.

**Comment by parente** [comment]
It's just the clean. I had old bower components. I'll update the clean target.
