### ISSUE TITLE
jupyter-js-output-area relocated to jupyter-js-notebook

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#67]
```
npm WARN deprecated jupyter-js-output-area@0.3.3: This code was merged into the jupyter-js-notebook package.
```

**Comment by jasongrout** [comment]
Were you using jupyter-js-output-area? Is it all right with you to incorporate it into jupyter-js-notebook?  What we found is that the usecase of an editor and a code cell were quite different, and we also decided to consolidate things into the jupyter-js-notebook repo to save lots of developer headache with lots of repos.  What do you think?

**Comment by parente** [comment]
We're using the output area as the "cell" view/model stand-in in a dashboard view that has no input area. 

* little animation: https://github.com/jupyter-incubator/dashboards_nodejs_app/issues/53#issuecomment-181529017
* use in code: https://github.com/jupyter-incubator/dashboards_nodejs_app/blob/master/public/js/dashboard.js#L136

I think it's OK that we have to pull in jupyter-js-notebook to get at it. A bit of bloat, but, not a show stopper.

I thought I heard some chatter about consolidating code into fewer repos, but at the same time having multiple npm packages within that repo. If that's still possible and on the table, it would help some I assume?

**Comment by jasongrout** [comment]
Nice! We might eventually have separate npm packages in the same repo, but that's a nightmare for another day :). It is a lot more manageable now with one repo.

**Comment by dalogsdon** [comment]
Pretty trivial change. We just webpack the output-area lib inside jupyter-js-notebook.
