### ISSUE TITLE
Read Urth.* defaults from config

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#69]
Currently hardcoded in dashboard.handlebars. See TODO at the bottom of that file.

**Comment by dalogsdon** [comment]
We can also begin purging 'Urth' starting with the default values.

**Comment by parente** [comment]
Re: purge ... except for the values in the ipynb file right? The dashboards extension is still using urth properties.

**Comment by dalogsdon** [comment]
Yes
