### ISSUE TITLE
Images do not resize to cell width

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards_nodejs_app#71]
In the dashboard notebook plugin, images in cells will resize to cell width:

![image](https://cloud.githubusercontent.com/assets/6362426/12893015/68f56bb8-ce54-11e5-9172-a01d66a01dbe.png)

In the dashboard server, images are always full size:

![image](https://cloud.githubusercontent.com/assets/6362426/12893034/8287b52c-ce54-11e5-9da2-90016e3e07fc.png)

This is using all Markdown cells with `<img>` elements.

**Comment by parente** [comment]
:+1: for the example

**Comment by dalogsdon** [comment]
Looks like notebook has different styling whether a cell is a code cell or text cell (markdown). If a code cell, overflow is visible in the `.output_subarea`. If a text cell, overflow-y is hidden. We will do the same to match the notebook authoring environment.
