### ISSUE TITLE
Dashboard list shows hidden folders

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards_nodejs_app#74]
Should we hide hidden files/folders in the dashboard list? Simple fix to give a bit of polish.

![missing signout](https://cloud.githubusercontent.com/assets/153745/12894501/13223ba6-ce65-11e5-9e44-9834f4730b35.png)

**Comment by poplav** [comment]
#76 should resolve the issue.

**Comment by dalogsdon** [comment]
I now realize there might be a broader scope here, since if we click on a subdirectory, it will try to load that as a notebook, which doesn't exist. I'll open a new issue for that and we will keep this one focused on filtering out hidden things.

**Comment by dalogsdon** [comment]
Opened #77 to deal with sub directories.
