### ISSUE TITLE
Dashboard list shows sub directories.

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards_nodejs_app#77]
The dashboard list page shows all contents of the data directory, which includes sub directories. However, selecting an entry in the list will attempt to load that as a notebook.

The `GET /dashboards/*` API does allow for sub directories, e.g. `GET /dashboards/subdir/foo.ipynb`. 

Should we support sub directories in the list page or remove support from the GET API?

**Comment by parente** [comment]
At some point in the near future, we might end up posting more than a notebook, but also frontend assets like imported declarative widgets, stylesheets, user defined styles, etc. In those cases, subdirs will sure help make sure that dependencies don't wind up overwriting one another.

**Comment by dalogsdon** [comment]
I have the initial implementation done in a branch. The tests don't pass, so I need to fix those.
