### ISSUE TITLE
Table styles missing

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#83]
Try https://github.com/jupyter-incubator/dashboards/blob/master/etc/notebooks/test/test_widget_overlap.ipynb in the notebook  dashboard preview and then here in the dashboard server. The table styling from the notebook environment is missing here. 

Related? When the table is wider than the window width, it does not overflow or scroll. In the notebook server, it overflows outside the allocated grid cell. The behavior should be consistent with the notebook.

<img width="978" alt="screen shot 2016-02-09 at 11 06 55 pm" src="https://cloud.githubusercontent.com/assets/153745/12938457/e6c095da-cf81-11e5-8471-1dbb7027cfae.png">

vs

<img width="913" alt="screen shot 2016-02-09 at 11 05 29 pm" src="https://cloud.githubusercontent.com/assets/153745/12938455/e438c6d4-cf81-11e5-8776-0a7bec7514ca.png">

**Comment by dalogsdon** [comment]
The question here is how to get the [`rendered_html`](https://github.com/jupyter/notebook/blob/b520b57f2f7bfc1cb9d9e6dd89c28e0a3b828285/notebook/static/notebook/less/renderedhtml.less) class on the proper sub-element so we can use the table styling.

If that is too difficult, we may have to just put the styling on the `.p-Widget` element.

**Comment by dalogsdon** [comment]
In addition to the table, I noticed the dropdown looked a little bit different in the dashboard server page. Upon investigation, I saw that the notebook compiles bootstrap CSS (less) and redefines some variable values. I did the same for this project and included a few variables to make the dropdown look similar. If we see more bootstrap styling differences or want to tweak them in any way (e.g. navbar) we can update the `variables.less` file.

**Comment by jhpedemonte** [comment]
Testing now. Noticed that in our server, the table does not overflow as it does in the Notebook. However, the selector that implements the `overflow: hidden` rule comes from Phosphor. I don't think we should change this -- I would assume that the Notebook will change to match our server once it goes "full Phosphor".
