### ISSUE TITLE
Heading and font size stylings differ between notebook dash preview and dashboard server

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#84]
Use https://github.com/jupyter-incubator/dashboards/blob/master/etc/notebooks/test/test_layout_basic.ipynb  as a reference. In dashboard server, the h1 is smaller than the h2, for example. Headings not bolded the same way. And so on. Makes layout difficult to get right.

<img width="1104" alt="screen shot 2016-02-09 at 11 09 35 pm" src="https://cloud.githubusercontent.com/assets/153745/12938476/45273bc4-cf82-11e5-9a4e-3a07d8283876.png">

vs 

<img width="1147" alt="screen shot 2016-02-09 at 11 09 16 pm" src="https://cloud.githubusercontent.com/assets/153745/12938478/4858aea4-cf82-11e5-9624-8018e369433e.png">

**Comment by dalogsdon** [comment]
We could copy styles that we want to match from [notebook/renderedHtml.less](https://github.com/jupyter/notebook/blob/932f85c7593b2eada7a2095bd1f30d3f6ea48115/notebook/static/notebook/less/renderedhtml.less)

**Comment by parente** [comment]
For the moment, I'd say try to match them exactly so that there's no intentional "surprises" when going from the notebook environment to the dashboard.

**Comment by dalogsdon** [comment]
I added styling to equalize dashboard server and dashboard notebook plugin. I added a `test_style_match.ipynb` that we can use to compare the two (warning: cougars).

One case that is a bit different is ordered and unordered lists. We are using transformime in the dashboard server, which is structuring the lists a bit differently than notebook does. However, jupyter-js-notebook does use it, so we will probably align with that unless they implement some custom transformers, which we could probably use anyway.

**Comment by parente** [comment]
> However, jupyter-js-notebook does use it, so we will probably align with that unless they implement some custom transformers, which we could probably use anyway.

Sounds good. We'll stick with the mantra of adopting the new stuff wherever possible.
