### ISSUE TITLE
Style login/list pages

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards_nodejs_app#88]
Currently we have default bootstrap style login and dashboard list. If we do issue #87, we could follow up with login and list styling to match. I put these in a separate issue as I feel they are less important than the navbar since they reside in their own pages which are not the main focus of dashboards.

**Comment by parente** [comment]
Also add better titles to the HTML. List page has none. Check login.

**Comment by dalogsdon** [comment]
List page got styled in conjunction with #87.
