### ISSUE TITLE
Apply rendered_html class to appropriately

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#93]
In #83, we decided to quick fix the styling problems by slapping the class on all output areas. This will probably have side-effects. We should revisit and find a way to apply it only when proper, when the output is actual HTML. This probably involves looking at the mimetypes in the `display_data` and `execute_result` messages in the `dashboards.js#messageHandlers`. At present, that function only receives a model. Adding a class dynamically would require a reference to the view as well. (Not sure such a reference is a good thing thinking about MVC design.)

**Comment by dalogsdon** [comment]
It looks like `OutputAreaModel` has a [phosphor-observablelist](https://github.com/phosphorjs/phosphor-observablelist) `outputs` that emits a signal when changed. We can add a changed handler to append the `rendered_html` class if the new value contains `text/html` data.
